### ISSUE TITLE
Member access within misaligned address when running with sanitizer

### ISSUE THREAD

**Issue by PoiXP** [FreeTDS/freetds#557]
See error when running a build with `-fsanitize=alignment` (https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html):
```
src/tds/iconv.c:1001:19: runtime error: member access within misaligned address 0x51000003cc99 for type 'TDS_BYTE_CONVERT2', which requires 2 byte alignment
0x51000003cc99: note: pointer points here
00 00 00  03 09 04 d0 00 34 00 00  00 00 00 00 ff ff ff ff  00 00 00 00 00 00 00 00  00 00 00 00 00
             ^ 
        #0 0x55aa53c134da in collate2charset
        #1 0x55aa53c1355d in tds_iconv_from_collate
        #2 0x55aa53c0c236 in tds_generic_get_info
        #3 0x55aa53c47503 in tds7_get_data_info
        #4 0x55aa53c409de in tds7_process_result
        #5 0x55aa53c3e7c8 in tds_process_tokens
        #6 0x55aa53bd9cef in dbsqlok
        #7 0x55aa53bd9262 in dbsqlexec
```

The build runs fine when this block is removed:
> https://github.com/FreeTDS/freetds/blob/9b979a7e355ead61b40fe957c6041329b67a7506/include/freetds/bytes.h#L155-L183

It seems unaligned access was used intentionally, but I'm lacking context why.

**Comment by freddy77** [comment]
Because on these machines misaligned access is not an undefined behaviour. But compiler cannot read comments so it complaints :smile: .
So, no practical issues. Still it would be nice to tell it to the compiler so it could avoid warning were it should not but tell were it's a real issue.
In code packaging network data this code is pretty common. However in other projects I use an alternative way to tell compiler that misaligned access is wanted and not an expected. I planned to use that syntax for compilers supporting it (gcc/clang/msvc that I know) but I forgot (well, it takes some time to test, especially having to test environments with bigendian encoding and others).

**Comment by freddy77** [comment]
Fixed in `master`.
